# Generated by Django 4.2.2 on 2023-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
