# Generated by Django 4.2.2 on 2023-06-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_category_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(blank=True, default=0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("inprogress", "In Progress"),
                    ("scheduled", "Scheduled"),
                ],
                default="inprogress",
                max_length=20,
            ),
        ),
    ]
