# Generated by Django 4.2.2 on 2023-06-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_task_priority_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
